name: Publish

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  java_build:
    name: Build and Publish Jar
    runs-on: ubuntu-latest
    env:
      # Needed to allow release version to be fetched and then sent to the publish artifact step
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        run: |
          # Strip git prefix from version
          RELEASE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && RELEASE_VERSION=$(echo $RELEASE_VERSION | sed -e 's/^v//')
          # Echo derived version for reference
          echo "Using version: $RELEASE_VERSION"
          # Export release version from step for use in publish artifact step
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          server-id: github

      - name: Build with Gradle
        run: ./gradlew clean build --refresh-dependencies -Pversion=$RELEASE_VERSION

      - name: Install gpg secret key
        if: github.event_name == 'release'
        run: |
          export GPG_TTY=$(tty)
          echo -n "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          echo -n "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode > $GITHUB_WORKSPACE/release.gpg

      - name: Publish to Gradle Plugin Repository
        working-directory: ${{ github.repository }}
        run: |
          ./gradlew publishPlugins \
            -Psemver.modifier=$RELEASE_VERSION \
            ${{ github.event.inputs.adhocCommand }} \
            -Pgradle.publish.key=${{ secrets.OSS_GRADLE_PUBLISH_KEY }} \
            -Pgradle.publish.secret=${{ secrets.OSS_GRADLE_PUBLISH_SECRET }} \
            -Psigning.keyId=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }} \
            -Psigning.password=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            -Psigning.secretKeyRingFile=release.gpg

